#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
